# Generated by Django 5.1.15 on 2026-05-26 21:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Sarlavha')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Muddati')),
                ('priority', models.CharField(choices=[('low', 'Past'), ('normal', "O'rta"), ('high', 'Yuqori')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('in_progress', 'Bajarilmoqda'), ('done', 'Bajarildi'), ('approved', 'Tasdiqlandi'), ('rejected', 'Rad etildi')], default='new', max_length=20)),
                ('kpi_points', models.PositiveIntegerField(default=10, verbose_name='KPI ball')),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('review_comment', models.TextField(blank=True, verbose_name='Sharh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to=settings.AUTH_USER_MODEL, verbose_name='Hodim')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Bergan kishi')),
            ],
            options={
                'verbose_name': 'Vazifa',
                'verbose_name_plural': 'Vazifalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskProof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='task_proofs/%Y/%m/')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proofs', to='tasks.task')),
            ],
            options={
                'verbose_name': 'Isbot',
                'verbose_name_plural': 'Isbotlar',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
