# Generated by Django 5.1.15 on 2026-05-26 21:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Sana')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='Kelgan vaqti')),
                ('check_in_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_in_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('check_in_distance_m', models.PositiveIntegerField(blank=True, null=True)),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='Ketgan vaqti')),
                ('check_out_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('late_minutes', models.PositiveIntegerField(default=0, verbose_name='Kechikish (daq)')),
                ('early_leave_minutes', models.PositiveIntegerField(default=0, verbose_name='Erta ketish (daq)')),
                ('worked_minutes', models.PositiveIntegerField(default=0, verbose_name='Ishlangan (daq)')),
                ('status', models.CharField(choices=[('present', 'Keldi'), ('late', 'Kechikdi'), ('absent', 'Kelmadi'), ('leave', "Ta'tilda"), ('weekend', 'Dam olish kuni')], default='present', max_length=20, verbose_name='Status')),
                ('is_weekend', models.BooleanField(default=False, verbose_name='Dam olish kuni')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Davomat',
                'verbose_name_plural': 'Davomat yozuvlari',
                'ordering': ['-date', '-check_in_time'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
