# Generated by Django 5.1.15 on 2026-05-29 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='check_in_ip',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='check_out_ip',
        ),
    ]
