# Generated by Django 5.1.15 on 2026-05-26 21:30

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('period', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bonuses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bonus',
                'verbose_name_plural': 'Bonuslar',
            },
        ),
        migrations.CreateModel(
            name='Penalty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('period', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='penalties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jarima',
                'verbose_name_plural': 'Jarimalar',
            },
        ),
        migrations.CreateModel(
            name='MonthlyPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='YYYY-MM', max_length=7)),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('weekend_extra', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('bonus_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('penalty_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('late_penalty_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('worked_days', models.PositiveIntegerField(default=0)),
                ('weekend_days', models.PositiveIntegerField(default=0)),
                ('late_minutes', models.PositiveIntegerField(default=0)),
                ('absent_days', models.PositiveIntegerField(default=0)),
                ('is_approved', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payrolls', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payrolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Oylik hisob-kitob',
                'verbose_name_plural': 'Oylik hisob-kitoblar',
                'ordering': ['-period'],
                'unique_together': {('user', 'period')},
            },
        ),
    ]
